### ISSUE TITLE
dev-entrypoint sleeps forever when using mysql instead of postgres

### ISSUE THREAD

**Issue by rmehner** [hintmedia/railsdock#9]
This is related to #8 

When you chose MySQL as database, the `dev-entrypoint` still points to Postgres and will sleep forever, waiting for something to respond on port 5432.

https://github.com/hintmedia/railsdock/blob/0e41dc97bf3ef6cea852e0647142bfa2defb56c8/lib/railsdock/templates/install/default/dev-entrypoint#L22-L24

The fix for MySQL should be to change it to this (haven't tried):

```sh
until nc -vz mysql 3306; do
  sleep 1
done
```

The fix for railsdock would probably be to make that line dependent on what you've chosen as database.

Again: thank you for reading and have a great day!

**Comment by nvick** [comment]
@rmehner thanks for bringing this to our attention.

**Comment by kyleboe** [comment]
Got this resolved and released version `0.2.0`! Thanks for reporting the bug 👍
